export const MODULE_NAME = 'page-cartogram-georeference';


export const CARTOGRAM_GEOREFERENCE_FETCH = 'CARTOGRAM_GEOREFERENCE_FETCH';
export const CARTOGRAM_GEOREFERENCE_FETCH_SUCCESS = 'CARTOGRAM_GEOREFERENCE_FETCH_SUCCESS';
export const CARTOGRAM_GEOREFERENCE_FETCH_FAILED = 'CARTOGRAM_GEOREFERENCE_FETCH_FAILED';


export const CARTOGRAM_GEOREFERENCE_ADJUST = 'CARTOGRAM_GEOREFERENCE_ADJUST';
export const CARTOGRAM_GEOREFERENCE_ADJUST_SUCCESS = 'CARTOGRAM_GEOREFERENCE_ADJUST_SUCCESS';
export const CARTOGRAM_GEOREFERENCE_ADJUST_FAILED = 'CARTOGRAM_GEOREFERENCE_ADJUST_FAILED';


export const CARTOGRAM_GEOREFERENCE_UPDATE = 'CARTOGRAM_GEOREFERENCE_UPDATE';
export const CARTOGRAM_GEOREFERENCE_UPDATE_SUCCESS = 'CARTOGRAM_GEOREFERENCE_UPDATE_SUCCESS';
export const CARTOGRAM_GEOREFERENCE_UPDATE_FAILED = 'CARTOGRAM_GEOREFERENCE_UPDATE_FAILED';


export const SUBMITTING = 'SUBMITTING';
