export const MODULE_NAME = 'cartogram-list';


export const CARTOGRAM_COLLECTIONS_SEARCH = 'CARTOGRAM_COLLECTIONS_SEARCH';
export const CARTOGRAM_COLLECTIONS_SEARCH_SUCCESS = 'CARTOGRAM_COLLECTIONS_SEARCH_SUCCESS';
export const CARTOGRAM_COLLECTIONS_SEARCH_FAILED = 'CARTOGRAM_COLLECTIONS_SEARCH_FAILED';


export const CARTOGRAM_COLLECTION_REMOVE = 'CARTOGRAM_COLLECTION_REMOVE';
export const CARTOGRAM_COLLECTION_REMOVE_SUCCESS = 'CARTOGRAM_COLLECTION_REMOVE_SUCCESS';
export const CARTOGRAM_COLLECTION_REMOVE_FAILED = 'CARTOGRAM_COLLECTION_REMOVE_FAILED';


export const ACCESS_TOKEN_READ = 'ACCESS_TOKEN_READ';
export const ACCESS_TOKEN_READ_SUCCESS = 'ACCESS_TOKEN_READ_SUCCESS';
export const ACCESS_TOKEN_READ_FAILED = 'ACCESS_TOKEN_READ_FAILED';
