export const MODULE_NAME = 'cartogram-create';

export const CARTOGRAM_CREATE = 'CARTOGRAM_CREATE';
export const CARTOGRAM_CREATE_SUCCESS = 'CARTOGRAM_CREATE_SUCCESS';
export const CARTOGRAM_CREATE_FAILED = 'CARTOGRAM_CREATE_FAILED';

export const CARGOTRAMS_SEARCH = 'CARGOTRAMS_SEARCH';
export const CARGOTRAMS_SEARCH_SUCCESS = 'CARGOTRAMS_SEARCH_SUCCESS';
export const CARGOTRAMS_SEARCH_FAILED = 'CARGOTRAMS_SEARCH_FAILED';

export const LOCATION_SEARCH = 'LOCATION_SEARCH';
export const LOCATION_SEARCH_SUCCESS = 'LOCATION_SEARCH_SUCCESS';
export const LOCATION_SEARCH_FAILED = 'LOCATION_SEARCH_FAILED';

export const ORGANIZATIONS_SEARCH = 'ORGANIZATIONS_SEARCH';
export const ORGANIZATIONS_SEARCH_SUCCESS = 'ORGANIZATIONS_SEARCH_SUCCESS';
export const ORGANIZATIONS_SEARCH_FAILED = 'ORGANIZATIONS_SEARCH_FAILED';

export const ACCESS_TOKEN_READ = 'ACCESS_TOKEN_READ';
export const ACCESS_TOKEN_READ_SUCCESS = 'ACCESS_TOKEN_READ_SUCCESS';
export const ACCESS_TOKEN_READ_FAILED = 'ACCESS_TOKEN_READ_FAILED';

export const INPUT_TIPS_SEARCH = 'INPUT_TIPS_SEARCH';
export const INPUT_TIPS_SEARCH_SUCCESS = 'INPUT_TIPS_SEARCH_SUCCESS';
export const INPUT_TIPS_SEARCH_FAILED = 'INPUT_TIPS_SEARCH_FAILED';

export const INPUT_TIP_SELECT = 'INPUT_TIP_SELECT';
export const INPUT_TIP_SELECT_SUCCESS = 'INPUT_TIP_SELECT_SUCCESS';
export const INPUT_TIP_SELECT_FAILED = 'INPUT_TIP_SELECT_FAILED';

export const SUBMITTING = 'SUBMITTING';
