export const MODULE_NAME = 'cartogram-create';

export const CARTOGRAMS_SEARCH = 'CARTOGRAMS_SEARCH';
export const CARTOGRAMS_SEARCH_SUCCESS = 'CARTOGRAMS_SEARCH_SUCCESS';
export const CARTOGRAMS_SEARCH_FAILED = 'CARTOGRAMS_SEARCH_FAILED';

export const CARTOGRAM_GEOJSON_FETCH = 'CARTOGRAM_GEOJSON_FETCH';
export const CARTOGRAM_GEOJSON_FETCH_SUCCESS = 'CARTOGRAM_GEOJSON_FETCH_SUCCESS';
export const CARTOGRAM_GEOJSON_FETCH_FAILED = 'CARTOGRAM_GEOJSON_FETCH_FAILED';
