export const MODULE_NAME = 'organization-list';


export const ORGANIZATIONS_SEARCH = 'ORGANIZATIONS_SEARCH';
export const ORGANIZATIONS_SEARCH_SUCCESS = 'ORGANIZATIONS_SEARCH_SUCCESS';
export const ORGANIZATIONS_SEARCH_FAILED = 'ORGANIZATIONS_SEARCH_FAILED';


export const ORGANIZATION_MEMBERS_SEARCH = 'ORGANIZATION_MEMBERS_SEARCH';
export const ORGANIZATION_MEMBERS_SEARCH_SUCCESS = 'ORGANIZATION_MEMBERS_SEARCH_SUCCESS';
export const ORGANIZATION_MEMBERS_SEARCH_FAILED = 'ORGANIZATION_MEMBERS_SEARCH_FAILED';


export const ORGANIZATION_INVITATIONS_SEARCH = 'ORGANIZATION_INVITATIONS_SEARCH';
export const ORGANIZATION_INVITATIONS_SEARCH_SUCCESS = 'ORGANIZATION_INVITATIONS_SEARCH_SUCCESS';
export const ORGANIZATION_INVITATIONS_SEARCH_FAILED = 'ORGANIZATION_INVITATIONS_SEARCH_FAILED';


export const ORGANIZATION_CREATE = 'ORGANIZATION_CREATE';
export const ORGANIZATION_CREATE_SUCCESS = 'ORGANIZATION_CREATE_SUCCESS';
export const ORGANIZATION_CREATE_FAILED = 'ORGANIZATION_CREATE_FAILED';


export const ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE';
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_SUCCESS';
export const ORGANIZATION_UPDATE_FAILED = 'ORGANIZATION_UPDATE_FAILED';


export const ORGANIZATION_REMOVE = 'ORGANIZATION_REMOVE';
export const ORGANIZATION_REMOVE_SUCCESS = 'ORGANIZATION_REMOVE_SUCCESS';
export const ORGANIZATION_REMOVE_FAILED = 'ORGANIZATION_REMOVE_FAILED';


export const ORGANIZATION_INVITATION_CREATE = 'ORGANIZATION_INVITATION_CREATE';
export const ORGANIZATION_INVITATION_CREATE_SUCCESS = 'ORGANIZATION_INVITATION_CREATE_SUCCESS';
export const ORGANIZATION_INVITATION_CREATE_FAILED = 'ORGANIZATION_INVITATION_CREATE_FAILED';


export const ORGANIZATION_EDIT = 'ORGANIZATION_EDIT';
export const ORGANIZATION_EDIT_SUCCESS = 'ORGANIZATION_EDIT_SUCCESS';
export const ORGANIZATION_EDIT_FAILED = 'ORGANIZATION_EDIT_FAILED';


export const ORGANIZATION_NAME_EDIT = 'ORGANIZATION_NAME_EDIT';
export const ORGANIZATION_NAME_EDIT_SUCCESS = 'ORGANIZATION_NAME_EDIT_SUCCESS';
export const ORGANIZATION_NAME_EDIT_FAILED = 'ORGANIZATION_NAME_EDIT_FAILED';


export const ORGANIZATION_INVITATION_ACCEPT = 'ORGANIZATION_INVITATION_ACCEPT';
export const ORGANIZATION_INVITATION_ACCEPT_SUCCESS = 'ORGANIZATION_INVITATION_ACCEPT_SUCCESS';
export const ORGANIZATION_INVITATION_ACCEPT_FAILED = 'ORGANIZATION_INVITATION_ACCEPT_FAILED';


export const ORGANIZATION_INVITATION_REJECT = 'ORGANIZATION_INVITATION_REJECT';
export const ORGANIZATION_INVITATION_REJECT_SUCCESS = 'ORGANIZATION_INVITATION_REJECT_SUCCESS';
export const ORGANIZATION_INVITATION_REJECT_FAILED = 'ORGANIZATION_INVITATION_REJECT_FAILED';


export const ORGANIZATION_MEMBER_REMOVE = 'ORGANIZATION_MEMBER_REMOVE';
export const ORGANIZATION_MEMBER_REMOVE_SUCCESS = 'ORGANIZATION_MEMBER_REMOVE_SUCCESS';
export const ORGANIZATION_MEMBER_REMOVE_FAILED = 'ORGANIZATION_MEMBER_REMOVE_FAILED';


export const USER_SELF_FETCH = 'USER_SELF_FETCH';
export const USER_SELF_FETCH_SUCCESS = 'USER_SELF_FETCH_SUCCESS';
export const USER_SELF_FETCH_FAILED = 'USER_SELF_FETCH_FAILED';


export const ORGANIZATION_ADD = 'ORGANIZATION_ADD';
export const ORGANIZATION_ADD_SUCCESS = 'ORGANIZATION_ADD_SUCCESS';
export const ORGANIZATION_ADD_FAILED = 'ORGANIZATION_ADD_FAILED';


export const TABLE_PAGINATION_CHANGE = 'TABLE_PAGINATION_CHANGE';
export const TABLE_PAGINATION_CHANGE_SUCCESS = 'TABLE_PAGINATION_CHANGE_SUCCESS';
export const TABLE_PAGINATION_CHANGE_FAILED = 'TABLE_PAGINATION_CHANGE_FAILED';


export const ORGANIZATION_CREATE_FORM = 'ORGANIZATION_CREATE_FORM';
export const ORGANIZATION_UPDATE_FORM = 'ORGANIZATION_UPDATE_FORM';
export const ORGANIZATION_INVITATION_CREATE_FORM = 'ORGANIZATION_INVITATION_CREATE_FORM';


export const ORGANIZATION_VIEW = 'ORGANIZATION_VIEW';
export const ORGANIZATION_VIEW_SUCCESS = 'ORGANIZATION_VIEW_SUCCESS';
export const ORGANIZATION_VIEW_FAILED = 'ORGANIZATION_VIEW_FAILED';


export const ORGANIZATION_INVITATION_ADD = 'ORGANIZATION_INVITATION_ADD';
export const ORGANIZATION_INVITATION_ADD_SUCCESS = 'ORGANIZATION_INVITATION_ADD_SUCCESS';
export const ORGANIZATION_INVITATION_ADD_FAILED = 'ORGANIZATION_INVITATION_ADD_FAILED';


export const TAB_ORGANIZATION_LIST = 'TAB_ORGANIZATION_LIST';
export const TAB_ORGANIZATION_INVITATION_LIST = 'TAB_ORGANIZATION_INVITATION_LIST';


export const ORGANIZATION_QUIT = 'ORGANIZATION_QUIT';
export const ORGANIZATION_QUIT_SUCCESS = 'ORGANIZATION_QUIT_SUCCESS';
export const ORGANIZATION_QUIT_FAILED = 'ORGANIZATION_QUIT_FAILED';
