export const MODULE_NAME = 'cartogram-update';

export const CARTOGRAM_COLLECTION_FETCH = 'CARTOGRAM_COLLECTION_FETCH';
export const CARTOGRAM_COLLECTION_FETCH_SUCCESS = 'CARTOGRAM_COLLECTION_FETCH_SUCCESS';
export const CARTOGRAM_COLLECTION_FETCH_FAILED = 'CARTOGRAM_COLLECTION_FETCH_FAILED';

export const CARTOGRAM_COLLECTION_UPDATE = 'CARTOGRAM_COLLECTION_UPDATE';
export const CARTOGRAM_COLLECTION_UPDATE_SUCCESS = 'CARTOGRAM_COLLECTION_UPDATE_SUCCESS';
export const CARTOGRAM_COLLECTION_UPDATE_FAILED = 'CARTOGRAM_COLLECTION_UPDATE_FAILED';

export const CARTOGRAMS_SEARCH = 'CARTOGRAMS_SEARCH';
export const CARTOGRAMS_SEARCH_SUCCESS = 'CARTOGRAMS_SEARCH_SUCCESS';
export const CARTOGRAMS_SEARCH_FAILED = 'CARTOGRAMS_SEARCH_FAILED';
