export const MODULE_NAME = 'layer-list';


export const LAYERS_SEARCH = 'LAYERS_SEARCH';
export const LAYERS_SEARCH_SUCCESS = 'LAYERS_SEARCH_SUCCESS';
export const LAYERS_SEARCH_FAILED = 'LAYERS_SEARCH_FAILED';


export const LAYER_REMOVE = 'LAYER_REMOVE';
export const LAYER_REMOVE_SUCCESS = 'LAYER_REMOVE_SUCCESS';
export const LAYER_REMOVE_FAILED = 'LAYER_REMOVE_FAILED';


export const QUERY_CONDITION_CHANGE = 'QUERY_CONDITION_CHANGE';
export const QUERY_CONDITION_CHANGE_SUCCESS = 'QUERY_CONDITION_CHANGE _SUCCESS';
export const QUERY_CONDITION_CHANGE_FAILED = 'QUERY_CONDITION_CHANGE_FAILED';


export const CHANGE_LOADING = 'CHANGE_LOADING';
