export const MODULE_NAME = 'password-reset';

export const PASSWORD_RESET = `${MODULE_NAME}--PASSWORD_RESET`;
export const PASSWORD_RESET_SUCCESS = `${MODULE_NAME}--PASSWORD_RESET_SUCCESS`;
export const PASSWORD_RESET_FAILED = `${MODULE_NAME}--PASSWORD_RESET_FAILED`;

export const FETCH_TOKEN = 'FETCH_TOKEN';
