export const MODULE_NAME = 'user-list';


export const USERS_SEARCH = 'USERS_SEARCH';
export const USERS_SEARCH_SUCCESS = 'USERS_SEARCH_SUCCESS';
export const USERS_SEARCH_FAILED = 'USERS_SEARCH_FAILED';


export const PLANS_SEARCH = 'PLANS_SEARCH';
export const PLANS_SEARCH_SUCCESS = 'PLANS_SEARCH_SUCCESS';
export const PLANS_SEARCH_FAILED = 'PLANS_SEARCH_FAILED';


export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';


export const USER_EDIT = 'USER_EDIT';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED';


export const QUERY_CONDITION_CHANGE = 'QUERY_CONDITION_CHANGE';
export const QUERY_CONDITION_CHANGE_SUCCESS = 'QUERY_CONDITION_CHANGE _SUCCESS';
export const QUERY_CONDITION_CHANGE_FAILED = 'QUERY_CONDITION_CHANGE_FAILED';


export const REGISTER_EMAIL_SEND = 'REGISTER_EMAIL_SEND';
export const REGISTER_EMAIL_SEND_SUCCESS = 'REGISTER_EMAIL_SEND _SUCCESS';
export const REGISTER_EMAIL_SEND_FAILED = 'REGISTER_EMAIL_SEND_FAILED';


export const USER_SELF_FETCH = 'USER_SELF_FETCH';
export const USER_SELF_FETCH_SUCCESS = 'USER_SELF_FETCH_SUCCESS';
export const USER_SELF_FETCH_FAILED = 'USER_SELF_FETCH_FAILED';


export const USER_IMPERSONATE = 'USER_IMPERSONATE';
export const USER_IMPERSONATE_SUCCESS = 'USER_IMPERSONATE_SUCCESS';
export const USER_IMPERSONATE_FAILED = 'USER_IMPERSONATE_FAILED';
