export const MODULE_NAME = 'cartogram-collection-routes';


export const CARTOGRAM_ROUTE_CREATE_FORM = 'CARTOGRAM_ROUTE_CREATE_FORM';
export const CARTOGRAM_ROUTE_EDIT_FORM = 'CARTOGRAM_ROUTE_EDIT_FORM';


export const DATA_LOAD = 'DATA_LOAD';
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS';
export const DATA_LOAD_FAILED = 'DATA_LOAD_FAILED';


export const CARTOGRAM_COLLECTION_FETCH = 'CARTOGRAM_COLLECTION_FETCH';
export const CARTOGRAM_COLLECTION_FETCH_SUCCESS = 'CARTOGRAM_COLLECTION_FETCH_SUCCESS';
export const CARTOGRAM_COLLECTION_FETCH_FAILED = 'CARTOGRAM_COLLECTION_FETCH_FAILED';


export const CARTOGRAM_ROUTES_SEARCH = 'CARTOGRAM_ROUTES_SEARCH';
export const CARTOGRAM_ROUTES_SEARCH_SUCCESS = 'CARTOGRAM_ROUTES_SEARCH_SUCCESS';
export const CARTOGRAM_ROUTES_SEARCH_FAILED = 'CARTOGRAM_ROUTES_SEARCH_FAILED';


export const CARTOGRAM_ROUTE_VIEW = 'CARTOGRAM_ROUTE_VIEW';
export const CARTOGRAM_ROUTE_VIEW_SUCCESS = 'CARTOGRAM_ROUTE_VIEW_SUCCESS';
export const CARTOGRAM_ROUTE_VIEW_FAILED = 'CARTOGRAM_ROUTE_VIEW_FAILED';


// 打开 添加 cartogram_route 界面 的action
export const CARTOGRAM_ROUTE_ADD = 'CARTOGRAM_ROUTE_ADD';
export const CARTOGRAM_ROUTE_ADD_SUCCESS = 'CARTOGRAM_ROUTE_ADD_SUCCESS';
export const CARTOGRAM_ROUTE_ADD_FAILED = 'CARTOGRAM_ROUTE_ADD_FAILED';


export const CARTOGRAM_ROUTE_CREATE = 'CARTOGRAM_ROUTE_CREATE';
export const CARTOGRAM_ROUTE_CREATE_SUCCESS = 'CARTOGRAM_ROUTE_CREATE_SUCCESS';
export const CARTOGRAM_ROUTE_CREATE_FAILED = 'CARTOGRAM_ROUTE_CREATE_FAILED';


// 打开 修改 cartogram_route 界面 的action
export const CARTOGRAM_ROUTE_EDIT = 'CARTOGRAM_ROUTE_EDIT';
export const CARTOGRAM_ROUTE_EDIT_SUCCESS = 'CARTOGRAM_ROUTE_EDIT_SUCCESS';
export const CARTOGRAM_ROUTE_EDIT_FAILED = 'CARTOGRAM_ROUTE_EDIT_FAILED';


export const CARTOGRAM_ROUTE_UPDATE = 'CARTOGRAM_ROUTE_UPDATE';
export const CARTOGRAM_ROUTE_UPDATE_SUCCESS = 'CARTOGRAM_ROUTE_UPDATE_SUCCESS';
export const CARTOGRAM_ROUTE_UPDATE_FAILED = 'CARTOGRAM_ROUTE_UPDATE_FAILED';


export const CARTOGRAM_ROUTE_REMOVE = 'CARTOGRAM_ROUTE_REMOVE';
export const CARTOGRAM_ROUTE_REMOVE_SUCCESS = 'CARTOGRAM_ROUTE_REMOVE_SUCCESS';
export const CARTOGRAM_ROUTE_REMOVE_FAILED = 'CARTOGRAM_ROUTE_REMOVE_FAILED';


export const FEATURES_SEARCH = 'FEATURES_SEARCH';
export const FEATURES_SEARCH_SUCCESS = 'FEATURES_SEARCH_SUCCESS';
export const FEATURES_SEARCH_FAILED = 'FEATURES_SEARCH_FAILED';


export const TABLE_PAGINATION_CHANGE = 'TABLE_PAGINATION_CHANGE';
export const TABLE_PAGINATION_CHANGE_SUCCESS = 'TABLE_PAGINATION_CHANGE_SUCCESS';
export const TABLE_PAGINATION_CHANGE_FAILED = 'TABLE_PAGINATION_CHANGE_FAILED';
