// @flow

export const MODULE_NAME = 'page-cartogram-draw';


export const CARTOGRAM_FETCH = 'CARTOGRAM_FETCH';
export const CARTOGRAM_FETCH_SUCCESS = 'CARTOGRAM_FETCH_SUCCESS';
export const CARTOGRAM_FETCH_FAILED = 'CARTOGRAM_FETCH_FAILED';


export const LAYERS_SEARCH = 'LAYERS_SEARCH';
export const LAYERS_SEARCH_SUCCESS = 'LAYERS_SEARCH_SUCCESS';
export const LAYERS_SEARCH_FAILED = 'LAYERS_SEARCH_FAILED';


export const DATA_LOAD = 'DATA_LOAD';
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS';
export const DATA_LOAD_FAILED = 'DATA_LOAD_FAILED';


export const MODE = 'MODE';

export const MODE_VIEW = `${MODE}_VIEW`;
export const MODE_EDIT = `${MODE}_EDIT`;
export const MODE_DRAW = `${MODE}_DRAW`;

export const MODE_EDIT_ADJUST = `${MODE_EDIT}_ADJUST`;
export const MODE_EDIT_MOVE = `${MODE_EDIT}_MOVE`;
export const MODE_EDIT_ROTATE = `${MODE_EDIT}_ROTATE`;
export const MODE_EDIT_COPY = `${MODE_EDIT}_COPY`;

export const MODE_DRAW_POINT = `${MODE_DRAW}_POINT`;

export const MODE_DRAW_CURVE = `${MODE_DRAW}_CURVE`;

export const MODE_DRAW_SURFACE = `${MODE_DRAW}_SURFACE`;
export const MODE_DRAW_SURFACE_FREEHAND = `${MODE_DRAW_SURFACE}_FREEHAND`;
export const MODE_DRAW_SURFACE_RECTANGLE = `${MODE_DRAW_SURFACE}_RECTANGLE`;


export const MODE_SWITCH = 'MODE_SWITCH';
export const MODE_SWITCH_SUCCESS = 'MODE_SWITCH_SUCCESS';
export const MODE_SWITCH_FAILED = 'MODE_SWITCH_FAILED';


export const ENTITIES_RESTORE = 'ENTITIES_RESTORE';
export const ENTITIES_RESTORE_SUCCESS = 'ENTITIES_RESTORE_SUCCESS';
export const ENTITIES_RESTORE_FAILED = 'ENTITIES_RESTORE_FAILED';


export const CARTOGRAM_RESTORE = 'CARTOGRAM_RESTORE';
export const CARTOGRAM_RESTORE_SUCCESS = 'CARTOGRAM_RESTORE_SUCCESS';
export const CARTOGRAM_RESTORE_FAILED = 'CARTOGRAM_RESTORE_FAILED';


export const LAYERS_RESTORE = 'LAYERS_RESTORE';
export const LAYERS_RESTORE_SUCCESS = 'LAYERS_RESTORE_SUCCESS';
export const LAYERS_RESTORE_FAILED = 'LAYERS_RESTORE_FAILED';


export const FEATURES_RESTORE = 'FEATURES_RESTORE';
export const FEATURES_RESTORE_SUCCESS = 'FEATURES_RESTORE_SUCCESS';
export const FEATURES_RESTORE_FAILED = 'FEATURES_RESTORE_FAILED';


export const CREATED_FEATURES_RESTORE = 'CREATED_FEATURES_RESTORE';
export const CREATED_FEATURES_RESTORE_SUCCESS = 'CREATED_FEATURES_RESTORE_SUCCESS';
export const CREATED_FEATURES_RESTORE_FAILED = 'CREATED_FEATURES_RESTORE_FAILED';


export const UPDATED_FEATURES_RESTORE = 'UPDATED_FEATURES_RESTORE';
export const UPDATED_FEATURES_RESTORE_SUCCESS = 'UPDATED_FEATURES_RESTORE_SUCCESS';
export const UPDATED_FEATURES_RESTORE_FAILED = 'UPDATED_FEATURES_RESTORE_FAILED';


export const REMOVED_FEATURES_RESTORE = 'REMOVED_FEATURES_RESTORE';
export const REMOVED_FEATURES_RESTORE_SUCCESS = 'REMOVED_FEATURES_RESTORE_SUCCESS';
export const REMOVED_FEATURES_RESTORE_FAILED = 'REMOVED_FEATURES_RESTORE_FAILED';


export const FEATURES_SEARCH = 'FEATURES_SEARCH';
export const FEATURES_SEARCH_SUCCESS = 'FEATURES_SEARCH_SUCCESS';
export const FEATURES_SEARCH_FAILED = 'FEATURES_SEARCH_FAILED';


// 标记feature为需要创建的feature
export const FEATURE_CREATE = 'FEATURE_CREATE';
export const FEATURE_CREATE_SUCCESS = 'FEATURE_CREATE_SUCCESS';
export const FEATURE_CREATE_FAILED = 'FEATURE_CREATE_FAILED';


// 标记feature为需要更新的feature
export const FEATURE_UPDATE = 'FEATURE_UPDATE';
export const FEATURE_UPDATE_SUCCESS = 'FEATURE_UPDATE_SUCCESS';
export const FEATURE_UPDATE_FAILED = 'FEATURE_UPDATE_FAILED';


// 标记feature为需要删除的feature
export const FEATURE_REMOVE = 'FEATURE_REMOVE';
export const FEATURE_REMOVE_SUCCESS = 'FEATURE_REMOVE_SUCCESS';
export const FEATURE_REMOVE_FAILED = 'FEATURE_REMOVE_FAILED';


// 将已标记的feature真正持久化到数据库（即发送到服务器）
export const FEATURE_PERSIST = 'FEATURE_PERSIST';
export const FEATURE_PERSIST_SUCCESS = 'FEATURE_PERSIST_SUCCESS';
export const FEATURE_PERSIST_FAILED = 'FEATURE_PERSIST_FAILED';


export const FEATURE_SELECT = 'FEATURE_SELECT';
export const FEATURE_SELECT_SUCCESS = 'FEATURE_SELECT_SUCCESS';
export const FEATURE_SELECT_FAILED = 'FEATURE_SELECT_FAILED';


export const FEATURE_DESELECT = 'FEATURE_DESELECT';
export const FEATURE_DESELECT_SUCCESS = 'FEATURE_DESELECT_SUCCESS';
export const FEATURE_DESELECT_FAILED = 'FEATURE_DESELECT_FAILED';


export const CARTOGRAM_GEOREFERENCE_FETCH = 'CARTOGRAM_GEOREFERENCE_FETCH';
export const CARTOGRAM_GEOREFERENCE_FETCH_SUCCESS = 'CARTOGRAM_GEOREFERENCE_FETCH_SUCCESS';
export const CARTOGRAM_GEOREFERENCE_FETCH_FAILED = 'CARTOGRAM_GEOREFERENCE_FETCH_FAILED';

export const INTERACTIVE_VERTEX_MARKER_RADIUS = 16;
export const INTERACTIVE_MARKER_RADIUS = 20;
