export const MODULE_NAME = 'profile-fetch';

export const PROFILE_FETCH = 'PROFILE_FETCH';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const PROFILE_FETCH_FAILED = 'PROFILE_FETCH_FAILED';

export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';

export const ORDERS_SEARCH = 'ORDERS_SEARCH';
export const ORDERS_SEARCH_SUCCESS = 'ORDERS_SEARCH_SUCCESS';
export const ORDERS_SEARCH_FAILED = 'ORDERS_SEARCH_FAILED';

export const INVOICES_SEARCH = 'INVOICES_SEARCH';
export const INVOICES_SEARCH_SUCCESS = 'INVOICES_SEARCH_SUCCESS';
export const INVOICES_SEARCH_FAILED = 'INVOICES_SEARCH_FAILED';

export const INVOICE_CREATE = 'INVOICE_CREATE';
export const INVOICE_CREATE_SUCCESS = 'INVOICE_CREATE_SUCCESS';
export const INVOICE_CREATE_FAILED = 'INVOICE_CREATE_FAILED';

export const ORDERS_SELECT = 'ORDERS_SELECT';

export const TOTAL_AMOUNT_COMPUTE = 'TOTAL_AMOUNT_COMPUTE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const PASSWORD_RESET = `${MODULE_NAME}--PASSWORD_RESET`;
export const PASSWORD_RESET_SUCCESS = `${MODULE_NAME}--PASSWORD_RESET_SUCCESS`;
export const PASSWORD_RESET_FAILED = `${MODULE_NAME}--PASSWORD_RESET_FAILED`;
