export const MODULE_NAME = 'layer-create';


export const LAYER_CREATE = 'LAYER_CREATE';
export const LAYER_CREATE_SUCCESS = 'LAYER_CREATE_SUCCESS';
export const LAYER_CREATE_FAILED = 'LAYER_CREATE_FAILED';


export const ORGANIZATIONS_SEARCH = 'ORGANIZATIONS_SEARCH';
export const ORGANIZATIONS_SEARCH_SUCCESS = 'ORGANIZATIONS_SEARCH_SUCCESS';
export const ORGANIZATIONS_SEARCH_FAILED = 'ORGANIZATIONS_SEARCH_FAILED';


export const USER_SELF_FETCH = 'USER_SELF_FETCH';
export const USER_SELF_FETCH_SUCCESS = 'USER_SELF_FETCH_SUCCESS';
export const USER_SELF_FETCH_FAILED = 'USER_SELF_FETCH_FAILED';


export const SUBMITTING = 'SUBMITTING';
