export const MODULE_NAME = 'cartogram-list';

export const CARTOGRAMS_SEARCH = 'CARTOGRAMS_SEARCH';
export const CARTOGRAMS_SEARCH_SUCCESS = 'CARTOGRAMS_SEARCH_SUCCESS';
export const CARTOGRAMS_SEARCH_FAILED = 'CARTOGRAMS_SEARCH_FAILED';

export const CARTOGRAM_REMOVE = 'CARTOGRAM_REMOVE';
export const CARTOGRAM_REMOVE_SUCCESS = 'CARTOGRAM_REMOVE_SUCCESS';
export const CARTOGRAM_REMOVE_FAILED = 'CARTOGRAM_REMOVE_FAILED';

export const QUERY_CONDITION_CHANGE = 'QUERY_CONDITION_CHANGE';
export const QUERY_CONDITION_CHANGE_SUCCESS = 'QUERY_CONDITION_CHANGE _SUCCESS';
export const QUERY_CONDITION_CHANGE_FAILED = 'QUERY_CONDITION_CHANGE_FAILED';

export const CHANGE_LOADING = 'CHANGE_LOADING';
