export const MODULE_NAME = 'cartogram-create';

export const CARTOGRAM_COLLECTION_CREATE = `${MODULE_NAME}--CARTOGRAM_COLLECTION_CREATE`;
export const CARTOGRAM_COLLECTION_CREATE_SUCCESS = `${MODULE_NAME}--CARTOGRAM_COLLECTION_CREATE_SUCCESS`;
export const CARTOGRAM_COLLECTION_CREATE_FAILED = `${MODULE_NAME}--CARTOGRAM_COLLECTION_CREATE_FAILED`;

export const CARTOGRAMS_SEARCH = `${MODULE_NAME}--CARTOGRAMS_SEARCH`;
export const CARTOGRAMS_SEARCH_SUCCESS = `${MODULE_NAME}--CARTOGRAMS_SEARCH_SUCCESS`;
export const CARTOGRAMS_SEARCH_FAILED = `${MODULE_NAME}--CARTOGRAMS_SEARCH_FAILED`;

export const ORGANIZATIONS_SEARCH = `${MODULE_NAME}--ORGANIZATIONS_SEARCH`;
export const ORGANIZATIONS_SEARCH_SUCCESS = `${MODULE_NAME}--ORGANIZATIONS_SEARCH_SUCCESS`;
export const ORGANIZATIONS_SEARCH_FAILED = `${MODULE_NAME}--ORGANIZATIONS_SEARCH_FAILED`;

export const SUBMITTING = 'SUBMITTING';
