// @flow

export const MODULE_NAME = 'plan-pricing';

export const USER_INFO_FETCH = 'USER_INFO_FETCH';
export const USER_INFO_FETCH_SUCCESS = 'USER_INFO_FETCH_SUCCESS';
export const USER_INFO_FETCH_FAILED = 'USER_INFO_FETCH_FAILED';

export const PLAN_LOAD = 'PLAN_LOAD';
export const PLAN_LOAD_SUCCESS = 'PLAN_LOAD_SUCCESS';
export const PLAN_LOAD_FAILED = 'PLAN_LOAD_FAILED';

export const PLAN_BY_LEVEL_FETCH = 'PLAN_BY_LEVEL_FETCH';
export const PLAN_BY_LEVEL_FETCH_SUCCESS = 'PLAN_BY_LEVEL_FETCH_SUCCESS';
export const PLAN_BY_LEVEL_FETCH_FAILED = 'PLAN_BY_LEVEL_FETCH_FAILED';

export const PLAN_SELECT = 'PLAN_SELECT';
export const PLAN_SELECT_SUCCESS = 'PLAN_SELECT_SUCCESS';
export const PLAN_SELECT_FAILED = 'PLAN_SELECT_FAILED';

export const PLAN_UNSELECT = 'PLAN_UNSELECT';
export const PLAN_UNSELECT_SUCCESS = 'PLAN_UNSELECT_SUCCESS';
export const PLAN_UNSELECT_FAILED = 'PLAN_UNSELECT_FAILED';

export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED';

export const WXPAY_INFO_FETCH = 'WXPAY_INFO_FETCH';
export const WXPAY_INFO_FETCH_SUCCESS = 'WXPAY_INFO_FETCH_SUCCESS';
export const WXPAY_INFO_FETCH_FAILED = 'WXPAY_INFO_FETCH_FAILED';

export const ORDER_FETCH = 'ORDER_FETCH';
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS';
export const ORDER_FETCH_FAILED = 'ORDER_FETCH_FAILED';

export const PAY_METHOD_SELECT = 'PAY_METHOD_SELECT';
export const PAY_METHOD_SELECT_SUCCESS = 'PAY_METHOD_SELECT_SUCCESS';
export const PAY_METHOD_SELECT_FAILED = 'PAY_METHOD_SELECT_FAILED';

export const PAY_METHOD_UNSELECT = 'PAY_METHOD_UNSELECT';
export const PAY_METHOD_UNSELECT_SUCCESS = 'PAY_METHOD_UNSELECT_SUCCESS';
export const PAY_METHOD_UNSELECT_FAILED = 'PAY_METHOD_UNSELECT_FAILED';

export const ORGANIZATION_SELECT = 'ORGANIZATION_SELECT';
export const ORGANIZATION_SELECT_SUCCESS = 'ORGANIZATION_SELECT_SUCCESS';
export const ORGANIZATION_SELECT_FAILED = 'ORGANIZATION_SELECT_FAILED';

export const ORGANIZATION_UNSELECT = 'ORGANIZATION_UNSELECT';
export const ORGANIZATION_UNSELECT_SUCCESS = 'ORGANIZATION_UNSELECT_SUCCESS';
export const ORGANIZATION_UNSELECT_FAILED = 'ORGANIZATION_UNSELECT_FAILED';

export const ORGANIZATIONS_SEARCH = 'ORGANIZATIONS_SEARCH';
export const ORGANIZATIONS_SEARCH_SUCCESS = 'ORGANIZATIONS_SEARCH_SUCCESS';
export const ORGANIZATIONS_SEARCH_FAILED = 'ORGANIZATIONS_SEARCH_FAILED';

export const PAYMENT_VALIDATE = 'PAYMENT_VALIDATE';
export const PAYMENT_VALIDATE_SUCCESS = 'PAYMENT_VALIDATE_SUCCESS';
export const PAYMENT_VALIDATE_FAILED = 'PAYMENT_VALIDATE_FAILED';

export const WITH_ALIPAY_CHECKOUT = 'WITH_ALIPAY_CHECKOUT';
export const WITH_ALIPAY_CHECKOUT_SUCCESS = 'WITH_ALIPAY_CHECKOUT_SUCCESS';
export const WITH_ALIPAY_CHECKOUT_FAILED = 'WITH_ALIPAY_CHECKOUT_FAILED';

export const WITH_WXPAY_CHECKOUT = 'WITH_WXPAY_CHECKOUT';
export const WITH_WXPAY_CHECKOUT_SUCCESS = 'WITH_WXPAY_CHECKOUT_SUCCESS';
export const WITH_WXPAY_CHECKOUT_FAILED = 'WITH_WXPAY_CHECKOUT_FAILED';
