export const MODULE_NAME = 'geometry-style-update';


export const GEOMETRY_STYLE_FETCH = 'GEOMETRY_STYLE_FETCH';
export const GEOMETRY_STYLE_FETCH_SUCCESS = 'GEOMETRY_STYLE_FETCH_SUCCESS';
export const GEOMETRY_STYLE_FETCH_FAILED = 'GEOMETRY_STYLE_FETCH_FAILED';


export const GEOMETRY_STYLE_UPDATE = 'GEOMETRY_STYLE_UPDATE';
export const GEOMETRY_STYLE_UPDATE_SUCCESS = 'GEOMETRY_STYLE_UPDATE_SUCCESS';
export const GEOMETRY_STYLE_UPDATE_FAILED = 'GEOMETRY_STYLE_UPDATE_FAILED';
