export const MODULE_NAME = 'plan-list';

export const PLANS_SEARCH = `PLANS_SEARCH`;
export const PLANS_SEARCH_SUCCESS = `PLANS_SEARCH_SUCCESS`;
export const PLANS_SEARCH_FAILED = `PLANS_SEARCH_FAILED`;

export const PLAN_CREATE = `PLAN_CREATE`;
export const PLAN_CREATE_SUCCESS = `PLAN_CREATE_SUCCESS`;
export const PLAN_CREATE_FAILED = `PLAN_CREATE_FAILED`;

export const PLAN_UPDATE = `PLAN_UPDATE`;
export const PLAN_UPDATE_SUCCESS = `PLAN_UPDATE_SUCCESS`;
export const PLAN_UPDATE_FAILED = `PLAN_UPDATE_FAILED`;

export const PLAN_REMOVE = `PLAN_REMOVE`;
export const PLAN_REMOVE_SUCCESS = `PLAN_REMOVE_SUCCESS`;
export const PLAN_REMOVE_FAILED = `PLAN_REMOVE_FAILED`;

export const PLAN_EDIT = `PLAN_EDIT`;
export const PLAN_EDIT_SUCCESS = `PLAN_EDIT_SUCCESS`;
export const PLAN_EDIT_FAILED = `PLAN_EDIT_FAILED`;

export const PLAN_AS_LEVEL_DEFAULT_MARK = `PLAN_AS_LEVEL_DEFAULT_MARK`;
export const PLAN_AS_LEVEL_DEFAULT_MARK_SUCCESS = `PLAN_AS_LEVEL_DEFAULT_MARK_SUCCESS`;
export const PLAN_AS_LEVEL_DEFAULT_MARK_FAILED = `PLAN_AS_LEVEL_DEFAULT_MARK_FAILED`;
